### ISSUE TITLE
Sun/Moon bad X positioning in PTR

### ISSUE THREAD

**Issue by AbuMaia** [workinghard/DigiMe#2]
Hello,

I don't know why, as I haven't yet been able to find the right settings to tweak to fix it yet, but on my Pebble Time Round, sunrise and moonrise are both chopped off by the edge of the screen, while sunset/moonset have quite a healthy margin from the edge. It appears that an X position number is off somewhere, though I haven't been able to find it yet. As far as I can tell, it shows the same way in Cloudpebble, though even there I haven't figured out how to make the emulator show times different than current time.

**Comment by workinghard** [comment]
The issue should be fixed in the next update. You can still experiment with the most recent source changes. And play with the new X offset in dayNightMask.h 
Please let me know which value works best because I don't have pebble round and have to rely on the emulator.

**Comment by AbuMaia** [comment]
18 seems to work best on my PTR while fiddling with the time/date setting on my phone. Thanks for the quick fix.

**Comment by workinghard** [comment]
And 18 it is. The new version is published and should be distributed soon. Thanks for testing.
